# Generated by Django 5.0.7 on 2024-08-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_of_dress', models.CharField(max_length=20)),
                ('hex_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mrp_price', models.PositiveIntegerField()),
                ('selling_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/products/')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('dress_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.dresstype')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size')),
            ],
        ),
    ]
